language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

branches:
  only:
    - master

os:
  - linux

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MOmSGUmQlEBdArqZgzvPq6Rc3fN/jqpHXgFqczCRZre8QOcokdzbkuhib5BntajR73y11gqzmPFFZ9sr+m3xEt7phM/PtxDcsZmtzy8gF5vLpY2HOvdN9rakp6uM2WSmWFv9T+Ebj3Ihd+yob5e4Tnszm4tJoJMCHO0JNW/thaU="
  matrix:
   - BUILD_TYPE=cmake     BUILD_MODE=Release
   - BUILD_TYPE=automake  BUILD_MODE=Debug
   - BUILD_TYPE=cmake     BUILD_MODE=Debug
   - BUILD_TYPE=automake  BUILD_MODE=Release

addons:
  coverity_scan:
    project:
      name: "mgerhardy/simpleai"
      description: "Build submitted via Travis CI"
    notification_email: martin.gerhardy@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make -j 4"
    branch_pattern: coverity_scan

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install lua5.2 liblua5.2-dev qt5-default qtbase5-dev -y

script:
  - .travis/configure.sh
  - .travis/cmake.sh

notifications:
  email: true

cache: apt
