language: cpp

sudo: false

compiler:
  - gcc
  - clang

branches:
  only:
    - master

os:
  - linux

addons:
  apt:
    packages:
    - g++-5
    - gcc-5
    - clang
    - make
    - cmake
    - autoconf
    - automake
    - libtool
    - build-essential
    - lua5.1
    - liblua5.2-dev
    - libgtest-dev
    sources:
    - ubuntu-toolchain-r-test

script:
  - ./autogen.sh
  - ./configure --prefix=/usr --enable-tests=yes
  - make
  - sudo make install
  - ./src/test/tests
  - ./configure --enable-tests=yes --enable-example=yes
  - make clean && make
  - ./configure --enable-tests=yes
  - make clean && make
  - ./configure --enable-example=yes
  - make clean && make
  - ./configure --enable-lua=no
  - make clean && make
  - ./configure --enable-lua=no --enable-tests=yes
  - make clean && make
  - ./configure --enable-debug --enable-gprof
  - make clean && make
  - cd src/debug && qmake -qt=qt5 && make
  - mkdir simpleai-build; cd simpleai-build; cmake -DSIMPLEAI_DEBUGGER=ON -DCMAKE_BUILD_TYPE=Release -G"Eclipse CDT4 - Unix Makefiles" ..; make

notifications:
  email: true
