language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

branches:
  only:
    - master

os:
  - linux

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MOmSGUmQlEBdArqZgzvPq6Rc3fN/jqpHXgFqczCRZre8QOcokdzbkuhib5BntajR73y11gqzmPFFZ9sr+m3xEt7phM/PtxDcsZmtzy8gF5vLpY2HOvdN9rakp6uM2WSmWFv9T+Ebj3Ihd+yob5e4Tnszm4tJoJMCHO0JNW/thaU="
  matrix:
   - BUILD_TYPE=cmake
   - BUILD_TYPE=automake

addons:
  coverity_scan:
    project:
      name: "mgerhardy/simpleai"
      description: "Build submitted via Travis CI"
    notification_email: martin.gerhardy@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make -j 4"
    branch_pattern: coverity_scan
  apt:
    packages:
    - g++-5
    - gcc-5
    - clang
    - make
    - cmake
    - autoconf
    - automake
    - libtool
    - build-essential
    - lua5.1
    - liblua5.2-dev
    - libgtest-dev
    sources:
    - ubuntu-toolchain-r-test

script:
  - gcc --version
  - clang --version
  - cmake --version
  - ls /usr/bin
  - "if [ $BUILD_TYPE == automake ]; then \
       ./autogen.sh
       ./configure --prefix=$PWD --enable-tests=yes
       make
       make install
       ./src/test/simpleai-tests
       make dist-clean
       ./configure --enable-tests=yes --enable-run=yes
       make
       make dist-clean
       ./configure --enable-tests=yes
       make
       make dist-clean
       ./configure --enable-run=yes
       make
       make dist-clean
       ./configure --enable-lua=no
       make
       make dist-clean
       ./configure --enable-lua=no --enable-tests=yes
       make
       make dist-clean
       ./configure --enable-debug --enable-gprof
       make
       make dist-clean
       cd src/debug
       qmake
       make
     fi"
  - "if [ $BUILD_TYPE == cmake ]; then \
       mkdir simpleai-build
       cd simpleai-build
       cmake -DSIMPLEAI_DEBUGGER=ON -DCMAKE_BUILD_TYPE=Release -G"Eclipse CDT4 - Unix Makefiles" ..
       make
     fi"

notifications:
  email: true

cache: apt
