language: cpp

sudo: false
dist: trusty

compiler:
- gcc
- clang

branches:
  only:
  - master

os:
- linux

env:
  global:
  - secure: MOmSGUmQlEBdArqZgzvPq6Rc3fN/jqpHXgFqczCRZre8QOcokdzbkuhib5BntajR73y11gqzmPFFZ9sr+m3xEt7phM/PtxDcsZmtzy8gF5vLpY2HOvdN9rakp6uM2WSmWFv9T+Ebj3Ihd+yob5e4Tnszm4tJoJMCHO0JNW/thaU=
  matrix:
  - BUILD_TYPE=cmake     BUILD_MODE=Release
  - BUILD_TYPE=automake  BUILD_MODE=Debug
  - BUILD_TYPE=cmake     BUILD_MODE=Debug
  - BUILD_TYPE=automake  BUILD_MODE=Release
  - BUILD_TYPE=doxygen   BUILD_MODE=Debug

matrix:
  exclude:
  - compiler: clang
    env: BUILD_TYPE=doxygen BUILD_MODE=Debug

addons:
  coverity_scan:
    project:
      name: mgerhardy/simpleai
      description: Build submitted via Travis CI
    notification_email: martin.gerhardy@gmail.com
    build_command_prepend: cmake .
    build_command: make -j 4
    branch_pattern: coverity_scan
  apt:
    packages:
    - doxygen
    - graphviz
    - qt5-default
    - qtbase5-dev

before_install:
- openssl aes-256-cbc -K $encrypted_9796cc8955c8_key -iv $encrypted_9796cc8955c8_iv
  -in .travis/travisci_rsa.enc -out .travis/travisci_rsa -d
- chmod 0600 .travis/travisci_rsa
- cp .travis/travisci_rsa ~/.ssh/id_rsa

script:
- ".travis/configure.sh"
- ".travis/cmake.sh"
- ".travis/doxygen.sh"

notifications:
  email: true

cache: apt
cache: ccache
