language: cpp

env:
  - CC="ccache gcc"

compiler:
  - gcc
  - clang

branches:
  only:
    - master

script:
  - ./autogen.sh
  - ./configure --prefix=/usr --enable-tests=yes
  - make
  - sudo make install
  - ./src/test/tests
  - ./configure --enable-tests=yes --enable-example=yes
  - make clean && make
  - ./configure --enable-tests=yes
  - make clean && make
  - ./configure --enable-example=yes
  - make clean && make
  - ./configure --enable-lua=no
  - make clean && make
  - ./configure --enable-lua=no --enable-tests=yes
  - make clean && make
  - ./configure --enable-debug --enable-gprof
  - make clean && make
  - cd src/debug && qmake -qt=qt5 && make

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default ccache

notifications:
  email: true

