language: cpp
compiler:
  - gcc
  - clang

script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - ./src/test/tests
  - cd src/debug && qmake -qt=qt5 && make

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y qt5-default

notifications:
  email: true

