language: cpp
compiler:
  - gcc
  - clang

script: ./configure && make && ./src/test/tests

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y qt5-default

notifications:
  email: true

