version: '{build}'

configuration: Release

platform:
  - x86
  - x64

environment:
  matrix:
    - generator: Visual Studio 12 2013
    - generator: Visual Studio 12 2013 Win64
    - generator: Visual Studio 12 2015
    - generator: Visual Studio 12 2015 Win64

branches:
  only:
  - master

clone_depth: 10

before_build:
  - cmd: cmake -DTOOLS=OFF -G "%generator%"

build:
  parallel: true
  project: simpleai.sln

artifacts:
  - name: Debugger
    path: simpleai-debugger.exe
  - name: Runner
    path: simpleai-run.exe

test_script:
  - cmd: simpleai-tests --gtest_output=xml:tests.xml

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))

matrix:
  fast_finish: true
